# Ejercicios Numpy
## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [1]:
#Importo librería numpy
import numpy as np

In [4]:
#Creo un array unidimensional.
array1D = np.random.randint(10,100,50)
print(array1D)
print('________________________________________________________________________')
#Uso un star, stop, step para encontrar los elementos en posiciones múltiples de 5.
print(f'Los elementos en posiciones múltiplos de 5 son:\n {array1D[::5]}')

[60 77 45 78 74 73 70 92 56 69 43 82 39 87 33 77 95 58 15 60 16 45 99 64
 53 86 76 81 89 36 22 98 80 63 96 32 61 69 33 48 31 52 30 89 43 44 84 58
 86 61]
________________________________________________________________________
Los elementos en posiciones múltiplos de 5 son:
 [60 73 43 77 16 86 22 32 31 44]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [17]:
#Creo otro array unidimensional con valores aleatorios.
array1D = np.random.randint(1, 21, 30)
print(array1D)
print('________________________________________________________________________')
#Vuelvo a usar un star, stop, step para encontrar los elementos en posiciones impares.
print(f'Los elementos en posiciones impares son:\n {array1D[1::2]}')


[18  2  6  6 16 17  4 15 19 13  9 19  8 19 12  2 20  3 17 14 12 12  4 16
 17  5 13 12  3 19]
________________________________________________________________________
Los elementos en posiciones impares son:
 [ 2  6 17 15 13 19 19  2  3 14 12 16  5 12 19]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [35]:
#Creo otro array bidimensional con valores aleatorios decimales que sean superiores al 1, así que utilizo uniform.
array2D = np.random.uniform(10,50,(4, 6))
print(array2D)
#Redondeo los resultados a dos decimales.
array_2D_redondeado = np.round(array2D, 2)
print('________________________________________________________________________')
#Accdeo a la última fila de la matriz.
print(f'Los elementos de la última fila son: {array_2D_redondeado[-1]}')



[[11.79773042 46.79226321 21.14375634 49.94845173 25.94849926 17.62332823]
 [19.57262657 41.32042989 28.34844858 32.968226   14.55099853 33.73680677]
 [13.98769625 36.60619891 23.57717098 39.3228587  43.792847   14.56622438]
 [40.64366021 39.26941105 34.43528776 26.45924447 46.97456087 29.15688645]]
________________________________________________________________________
Los elementos de la última fila son: [40.64 39.27 34.44 26.46 46.97 29.16]


**BONUS**: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [37]:
array3D = np.random.randint(0,101,(2,3,5))
print(array3D)
print('________________________________________________________________________')


[[[38 31 86 45 83]
  [32 36 56 70 54]
  [70 57 81 67 64]]

 [[12 61  7  9 13]
  [56 86 68 78  4]
  [95 24 97 72 87]]]
________________________________________________________________________


## Reshape y Transpose:
1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [42]:
#Creo un array tridimensional con valores aleatorios.
array3D = np.random.randint(1,101,(2,3,4))
print(array3D)
print('________________________________________________________________________')
#Las columnas y filas tienen que seguir sumando 24. Sumo las filas de las dos matrices (o multiplico 2x3) y mantengo numero columnas para poder cambiar la forma.)
array2D = np.reshape(array3D,(6,4))
print(array2D)

[[[29 52 58 57]
  [59  9 73 83]
  [89 59 42  1]]

 [[88 99 42 26]
  [21 99  4 58]
  [50 79 73 49]]]
________________________________________________________________________
[[29 52 58 57]
 [59  9 73 83]
 [89 59 42  1]
 [88 99 42 26]
 [21 99  4 58]
 [50 79 73 49]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.


In [44]:
#Creo un array tridimensional con valores enteros aleatorios.
array3D = np.random.randint(1,61,(3,4,5))
print(array3D)
print('________________________________________________________________________')
#Las columnas y filas tienen que seguir sumando 60. Sumo las filas de las dos matrices (o multiplico 3x4) y mantengo numero columnas para cambiar la matriz de forma.)
array2D= np.reshape(array3D, (12,5))
print(array2D)

[[[26 29 16 22 59]
  [41 20 45  1 23]
  [32 10 44 51 27]
  [ 5 14  1  6 25]]

 [[ 5 53 40 12 49]
  [58 51 42 43 60]
  [41 51 30 19  7]
  [54 18 53 56  1]]

 [[26 36  5 54 50]
  [41 58  7 59 46]
  [ 7 40 56 42 25]
  [ 5 13 27 43 19]]]
________________________________________________________________________
[[26 29 16 22 59]
 [41 20 45  1 23]
 [32 10 44 51 27]
 [ 5 14  1  6 25]
 [ 5 53 40 12 49]
 [58 51 42 43 60]
 [41 51 30 19  7]
 [54 18 53 56  1]
 [26 36  5 54 50]
 [41 58  7 59 46]
 [ 7 40 56 42 25]
 [ 5 13 27 43 19]]



3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [47]:
#Uilizo el array del ejercicio anterior.
array3D = np.random.randint(1,61,(3,4,5))
print(array3D)
print('________________________________________________________________________')
#Uso la indexación de las dimensiones del array3D para cambiar el orden de los ejes como pide el enunciado.
array_cambio_ejes = np.transpose(array3D, axes=(2,1,0))
print(array_cambio_ejes)

[[[20 26 52 46 26]
  [ 2 28 31 39 37]
  [57 53 18  1 55]
  [27 37  7 21 18]]

 [[26 36 28 43 43]
  [52 57  4 36  7]
  [56 17 53 17 18]
  [41 29 20 46 20]]

 [[26 13 60 21 25]
  [52 33 56 41 27]
  [58 10 56 14 45]
  [49 59  3 14 12]]]
________________________________________________________________________
[[[20 26 26]
  [ 2 52 52]
  [57 56 58]
  [27 41 49]]

 [[26 36 13]
  [28 57 33]
  [53 17 10]
  [37 29 59]]

 [[52 28 60]
  [31  4 56]
  [18 53 56]
  [ 7 20  3]]

 [[46 43 21]
  [39 36 41]
  [ 1 17 14]
  [21 46 14]]

 [[26 43 25]
  [37  7 27]
  [55 18 45]
  [18 20 12]]]


4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [48]:
#Uilizo el array del ejercicio anterior.
array3D = np.random.randint(1,61,(3,4,5))
print(array3D)
print('________________________________________________________________________')
#Uso la indexación de las dimensiones del array3D para cambiar el orden de los ejes como pide el enunciado.
array_cambio_ejes = np.transpose(array3D, axes=(0,2,1))
print(array_cambio_ejes)

[[[52  1 21 49 10]
  [27 42 14 15 39]
  [54 57 48 26  7]
  [ 7 17 33 43 18]]

 [[20  9 20 12 24]
  [ 3 56 35 49 17]
  [20 11 50 33 32]
  [29 37 56 18 49]]

 [[53  3 25  2 53]
  [39  5 12 21 51]
  [59 11 17 43 37]
  [15 33  6 21 42]]]
________________________________________________________________________
[[[52 27 54  7]
  [ 1 42 57 17]
  [21 14 48 33]
  [49 15 26 43]
  [10 39  7 18]]

 [[20  3 20 29]
  [ 9 56 11 37]
  [20 35 50 56]
  [12 49 33 18]
  [24 17 32 49]]

 [[53 39 59 15]
  [ 3  5 11 33]
  [25 12 17  6]
  [ 2 21 43 21]
  [53 51 37 42]]]


**3. Preguntas teóricas:**

*- ¿Qué diferencia existe entre el reshape y el transpose?*
Reshape cambia la forma y Transpose los ejes.

*- ¿Y entre el transpose y el swapaxes?*
Swapaxes intercambia dos ejes específicos entre sí y Transpose puede intercambiarlos todos.

## Funciones Aritméticas y Estadísticas:
1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [5]:
#Creo un array tridimensional con números decimales.
array3D = np.random.rand(2,3,5)
#Redondeo los resultados para que solo tengan 1 decimal.
array_redondeado = np.round(array3D, 1)
print(array_redondeado)


[[[0.7 0.8 0.4 0.8 0.7]
  [0.1 0.5 0.6 0.3 1. ]
  [0.2 0.3 0.9 0.7 0.8]]

 [[0.7 0.5 0.6 0.2 0.5]
  [0.6 0.2 0.1 0.8 0.7]
  [0.1 0.7 0.9 1.  0.7]]]


2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [79]:
#Creo el array vacío con las dimensiones del array anterior usando empty.
array_vacio= np.empty((2,3,5))
print(array_vacio)
#Calculo la media del array
print('________________________________________________________________________')
media_array = array_vacio.mean()
print(f'El valor medio del array es de: {media_array}')
print('________________________________________________________________________')
#Reemplazo los valores que coincidan con la media por la letra A, sino lo dejo por los valores del array vacío.
array_reemplazo_A = np.where(array_vacio == media_array, "A", array_vacio)
print(array_reemplazo_A)
print('________________________________________________________________________')
#Reemplazo los valores que sean mayores a la media por la letra B, sino lo dejo por los valores del array vacío.
array_reemplazo_B = np.where(array_vacio > media_array, "B", array_reemplazo_A)
print(array_reemplazo_B)
print('________________________________________________________________________')
#Reemplazo los valores que sean menores a la media por la letra C, sino lo dejo por los valores del array vacío.
array_reemplazo_C = np.where(array_vacio < media_array, "C", array_reemplazo_B)
print(array_reemplazo_C)
print('________________________________________________________________________')
#Calculo el valor máximo.
max_array = np.max(array_vacio)
print(f'El valor máximo del array es: {max_array}')
print('________________________________________________________________________')
#Reemplazo los valores que sean iguales al valor máximo por la letra D, sino lo dejo por los valores del array vacío.
array_reemplazo_D = np.where(array_vacio == max_array, "D", array_reemplazo_C)
print(array_reemplazo_D)
print('________________________________________________________________________')
#Calculo el valor mínimo.
min_array = np.min(array_vacio)
print(f'El valor mínimo del array es: {min_array}')
print('________________________________________________________________________')
#Reemplazo los valores que sean iguales al valor mínimo por la letra E, sino lo dejo por los valores del array vacío.
array_reemplazo_E = np.where(array_vacio == min_array, "E", array_reemplazo_D)
print(array_reemplazo_E)



[[[0.13 0.01 0.39 0.73 0.54]
  [0.75 0.19 0.23 0.16 0.96]
  [0.34 0.45 0.01 0.42 0.85]]

 [[0.47 0.16 0.49 0.45 0.37]
  [0.29 0.88 0.77 0.19 0.36]
  [0.56 0.5  0.19 0.5  0.93]]]
________________________________________________________________________
El valor medio del array es de: 0.4423333333333333
________________________________________________________________________
[[['0.13' '0.01' '0.39' '0.73' '0.54']
  ['0.75' '0.19' '0.23' '0.16' '0.96']
  ['0.34' '0.45' '0.01' '0.42' '0.85']]

 [['0.47' '0.16' '0.49' '0.45' '0.37']
  ['0.29' '0.88' '0.77' '0.19' '0.36']
  ['0.56' '0.5' '0.19' '0.5' '0.93']]]
________________________________________________________________________
[[['0.13' '0.01' '0.39' 'B' 'B']
  ['B' '0.19' '0.23' '0.16' 'B']
  ['0.34' 'B' '0.01' '0.42' 'B']]

 [['B' '0.16' 'B' 'B' '0.37']
  ['0.29' 'B' 'B' '0.19' '0.36']
  ['B' 'B' '0.19' 'B' 'B']]]
________________________________________________________________________
[[['C' 'C' 'C' 'B' 'B']
  ['B' 'C' 'C' 'C' 'B']
  