# Ejercicios Numpy
## Creación y Indexación:

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [2]:
#Importo librería numpy
import numpy as np

In [3]:
#Creo un array unidimensional.
array1D = np.random.randint(10,100,50)
print(array1D)
print('________________________________________________________________________')
#Uso un star, stop, step para encontrar los elementos en posiciones múltiples de 5.
print(f'Los elementos en posiciones múltiplos de 5 son:\n {array1D[::5]}')

[77 50 42 43 28 75 61 57 23 39 49 60 59 90 32 66 35 47 93 42 12 48 29 61
 71 18 15 41 50 37 29 95 43 33 77 77 61 54 61 64 49 32 38 49 54 80 70 24
 46 59]
________________________________________________________________________
Los elementos en posiciones múltiplos de 5 son:
 [77 75 49 66 12 18 29 77 49 80]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [4]:
#Creo otro array unidimensional con valores aleatorios.
array1D = np.random.randint(1, 21, 30)
print(array1D)
print('________________________________________________________________________')
#Vuelvo a usar un star, stop, step para encontrar los elementos en posiciones impares.
print(f'Los elementos en posiciones impares son:\n {array1D[1::2]}')


[14 19 19 15 12  2  1  7 16 18 10  3  1 13  2 10 20  3 13 13 15 20 13  8
  3 13  5 13 20  6]
________________________________________________________________________
Los elementos en posiciones impares son:
 [19 15  2  7 18  3 13 10  3 13 20  8 13 13  6]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [17]:
#Creo otro array bidimensional con valores aleatorios decimales que sean superiores al 1, así que utilizo uniform.
array2D = np.random.uniform(10,50, (4, 6))
print(array2D)
#Redondeo los resultados a dos decimales.
array_2D_redondeado = np.round(array2D, 2)
print('________________________________________________________________________')
#Accedo a la última fila de la matriz.
print(f'Los elementos de la última fila son: {array_2D_redondeado[-1]}')



[[26.76946609 28.71311046 47.04304066 19.49728821 15.93156248 46.07533459]
 [21.37005466 36.48892306 28.1138213  38.93601729 12.67630313 22.98332255]
 [21.98534406 18.12074553 32.47110472 19.45360121 45.76827803 48.61302281]
 [38.17490849 10.0140036  40.3512855  10.69000338 36.71763789 13.52598111]]
________________________________________________________________________
Los elementos de la última fila son: [38.17 10.01 40.35 10.69 36.72 13.53]


In [18]:
#Otra forma de solucionarlo sería utilizando este código:
array_2D = np.random.random_sample((4, 6)).round(2) + 1
print(array_2D)
print('________________________________________________________________________')
#Accedo a la última fila de la matriz.
print(f'Los elementos de la última fila son: {array_2D[-1]}')


[[1.79 1.15 1.13 1.33 1.79 1.83]
 [1.61 1.63 1.78 2.   1.42 1.95]
 [1.9  1.26 1.94 1.84 1.44 1.62]
 [1.13 1.47 1.85 1.65 1.6  1.43]]
________________________________________________________________________
Los elementos de la última fila son: [1.13 1.47 1.85 1.65 1.6  1.43]


**BONUS**: Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [7]:
array3D = np.random.randint(0,101,(2,3,5))
print(array3D)
print('________________________________________________________________________')


[[[55 17 74 23 94]
  [ 9 73 96 66 83]
  [49 55  0  9 62]]

 [[81 70 78 83 78]
  [41 75 38 87 63]
  [ 7 77 30 90 87]]]
________________________________________________________________________


## Reshape y Transpose:
1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [8]:
#Creo un array tridimensional con valores aleatorios.
array3D = np.random.randint(1,101,(2,3,4))
print(array3D)
print('________________________________________________________________________')
#Las columnas y filas tienen que seguir sumando 24. Sumo las filas de las dos matrices (o multiplico 2x3) y mantengo numero columnas para poder cambiar la forma.)
array2D = np.reshape(array3D,(6,4))
print(array2D)

[[[34 26 18 49]
  [80 66  6 62]
  [35 71 97 13]]

 [[92 38 11 90]
  [ 1 45 90 98]
  [15 20 28 38]]]
________________________________________________________________________
[[34 26 18 49]
 [80 66  6 62]
 [35 71 97 13]
 [92 38 11 90]
 [ 1 45 90 98]
 [15 20 28 38]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.


In [9]:
#Creo un array tridimensional con valores enteros aleatorios.
array3D = np.random.randint(1,61,(3,4,5))
print(array3D)
print('________________________________________________________________________')
#Las columnas y filas tienen que seguir sumando 60. Sumo las filas de las dos matrices (o multiplico 3x4) y mantengo numero columnas para cambiar la matriz de forma.)
array2D= np.reshape(array3D, (12,5))
print(array2D)

[[[31 41 51  7 45]
  [55  9 34  1  4]
  [33  5 54  5 22]
  [59 54 30 15 32]]

 [[40 12 58 19 28]
  [35 57 28 13 21]
  [17 20  3 22 21]
  [37 32 38 15 56]]

 [[52 40 39 15 38]
  [17 25  8 12 23]
  [14 38 40 28 38]
  [ 7 46 47 26  6]]]
________________________________________________________________________
[[31 41 51  7 45]
 [55  9 34  1  4]
 [33  5 54  5 22]
 [59 54 30 15 32]
 [40 12 58 19 28]
 [35 57 28 13 21]
 [17 20  3 22 21]
 [37 32 38 15 56]
 [52 40 39 15 38]
 [17 25  8 12 23]
 [14 38 40 28 38]
 [ 7 46 47 26  6]]



3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [10]:
#Uilizo el array del ejercicio anterior.
array3D = np.random.randint(1,61,(3,4,5))
print(array3D)
print('________________________________________________________________________')
#Uso la indexación de las dimensiones del array3D para cambiar el orden de los ejes como pide el enunciado.
array_cambio_ejes = np.transpose(array3D, axes=(2,1,0))
print(array_cambio_ejes)

[[[51 57 43 27 55]
  [39 40  2 10  7]
  [31 13  3 43 52]
  [48 37 42  1 14]]

 [[ 5 57  7 45 55]
  [21 39 30  6 40]
  [11 40 16 23 31]
  [41 17 50 24 16]]

 [[ 8  4 48 35 40]
  [59 25 43 59 55]
  [47  8 50 36 23]
  [ 9 29 18 28 24]]]
________________________________________________________________________
[[[51  5  8]
  [39 21 59]
  [31 11 47]
  [48 41  9]]

 [[57 57  4]
  [40 39 25]
  [13 40  8]
  [37 17 29]]

 [[43  7 48]
  [ 2 30 43]
  [ 3 16 50]
  [42 50 18]]

 [[27 45 35]
  [10  6 59]
  [43 23 36]
  [ 1 24 28]]

 [[55 55 40]
  [ 7 40 55]
  [52 31 23]
  [14 16 24]]]


4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [11]:
#Uilizo el array del ejercicio anterior.
array3D = np.random.randint(1,61,(3,4,5))
print(array3D)
print('________________________________________________________________________')
#Uso la indexación de las dimensiones del array3D para cambiar el orden de los ejes como pide el enunciado.
array_cambio_ejes = np.transpose(array3D, axes=(0,2,1))
print(array_cambio_ejes)

[[[43 15  1  1 12]
  [10 14 30 35  4]
  [25 30 28 57 59]
  [56 52 28 27 18]]

 [[ 7 13 42 13 31]
  [58 32  9 39 10]
  [20 18 15 31 27]
  [19 47 33 34 24]]

 [[ 8 22  3  5 45]
  [44 49 47 17 18]
  [48 21 33  3 27]
  [10 43 13 20 55]]]
________________________________________________________________________
[[[43 10 25 56]
  [15 14 30 52]
  [ 1 30 28 28]
  [ 1 35 57 27]
  [12  4 59 18]]

 [[ 7 58 20 19]
  [13 32 18 47]
  [42  9 15 33]
  [13 39 31 34]
  [31 10 27 24]]

 [[ 8 44 48 10]
  [22 49 21 43]
  [ 3 47 33 13]
  [ 5 17  3 20]
  [45 18 27 55]]]


**3. Preguntas teóricas:**

*- ¿Qué diferencia existe entre el reshape y el transpose?*
Reshape cambia la forma y Transpose los ejes.

*- ¿Y entre el transpose y el swapaxes?*
Swapaxes intercambia dos ejes específicos entre sí y Transpose puede intercambiarlos todos.

## Funciones Aritméticas y Estadísticas:
1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [12]:
#Creo un array tridimensional con números decimales.
array3D = np.random.rand(2,3,5)
#Redondeo los resultados para que solo tengan 1 decimal.
array_redondeado = np.round(array3D, 1)
print(array_redondeado)


[[[0.4 0.5 0.  0.8 0.7]
  [0.  0.9 0.9 0.1 0.5]
  [0.7 0.4 0.7 0.9 0.8]]

 [[0.9 0.2 0.7 0.4 0.1]
  [0.  0.2 0.2 0.1 0.3]
  [0.9 0.1 0.8 0.5 0.8]]]


2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".

Si el valor del array es mayor que la media, se reemplaza por "B".

Si el valor del array es menor que la media, se reemplaza por "C".

Si el valor es igual que el máximo, se reemplaza por "D".

Si el valor es igual que el mínimo, se reemplaza por "E".

In [13]:
#Creo el array vacío con las dimensiones del array anterior usando empty.
array_vacio= np.empty((2,3,5))
print(array_vacio)
#Calculo la media del array
print('________________________________________________________________________')
media_array = array_vacio.mean()
print(f'El valor medio del array es de: {media_array}')
print('________________________________________________________________________')
#Reemplazo los valores que coincidan con la media por la letra A, sino lo dejo por los valores del array vacío.
array_reemplazo_A = np.where(array_vacio == media_array, "A", array_vacio)
print(array_reemplazo_A)
print('________________________________________________________________________')
#Reemplazo los valores que sean mayores a la media por la letra B, sino lo dejo por los valores del array vacío.
array_reemplazo_B = np.where(array_vacio > media_array, "B", array_reemplazo_A)
print(array_reemplazo_B)
print('________________________________________________________________________')
#Reemplazo los valores que sean menores a la media por la letra C, sino lo dejo por los valores del array vacío.
array_reemplazo_C = np.where(array_vacio < media_array, "C", array_reemplazo_B)
print(array_reemplazo_C)
print('________________________________________________________________________')
#Calculo el valor máximo.
max_array = np.max(array_vacio)
print(f'El valor máximo del array es: {max_array}')
print('________________________________________________________________________')
#Reemplazo los valores que sean iguales al valor máximo por la letra D, sino lo dejo por los valores del array vacío.
array_reemplazo_D = np.where(array_vacio == max_array, "D", array_reemplazo_C)
print(array_reemplazo_D)
print('________________________________________________________________________')
#Calculo el valor mínimo.
min_array = np.min(array_vacio)
print(f'El valor mínimo del array es: {min_array}')
print('________________________________________________________________________')
#Reemplazo los valores que sean iguales al valor mínimo por la letra E, sino lo dejo por los valores del array vacío.
array_reemplazo_E = np.where(array_vacio == min_array, "E", array_reemplazo_D)
print(array_reemplazo_E)



[[[0.4 0.5 0.  0.8 0.7]
  [0.  0.9 0.9 0.1 0.5]
  [0.7 0.4 0.7 0.9 0.8]]

 [[0.9 0.2 0.7 0.4 0.1]
  [0.  0.2 0.2 0.1 0.3]
  [0.9 0.1 0.8 0.5 0.8]]]
________________________________________________________________________
El valor medio del array es de: 0.48333333333333345
________________________________________________________________________
[[['0.4' '0.5' '0.0' '0.8' '0.7']
  ['0.0' '0.9' '0.9' '0.1' '0.5']
  ['0.7' '0.4' '0.7' '0.9' '0.8']]

 [['0.9' '0.2' '0.7' '0.4' '0.1']
  ['0.0' '0.2' '0.2' '0.1' '0.3']
  ['0.9' '0.1' '0.8' '0.5' '0.8']]]
________________________________________________________________________
[[['0.4' 'B' '0.0' 'B' 'B']
  ['0.0' 'B' 'B' '0.1' 'B']
  ['B' '0.4' 'B' 'B' 'B']]

 [['B' '0.2' 'B' '0.4' '0.1']
  ['0.0' '0.2' '0.2' '0.1' '0.3']
  ['B' '0.1' 'B' 'B' 'B']]]
________________________________________________________________________
[[['C' 'B' 'C' 'B' 'B']
  ['C' 'B' 'B' 'C' 'B']
  ['B' 'C' 'B' 'B' 'B']]

 [['B' 'C' 'B' 'C' 'C']
  ['C' 'C' 'C' 'C' 'C']
  